spring:
  application:
    name: product-service
  data:
    mongodb:
      host: localhost
      port: 27017
      database: product-db
  cloud:
    stream:
      defaultBinder: kafka
      default.contentType: application/json
      bindings:
        consumeEvent-in-0:
          destination: products
          group: productGroup
          maxAttempts: 3
          backOffInitialInterval: 500
          backOffMaxInterval: 1000
          backOffMultiplier: 2.0
      kafka:
        enableDlq: true
        binder:
          brokers: 127.0.0.1
          defaultBrokerPort: 9092
server:
  port: 7001
logging:
  level:
    root: INFO
    com.microservices: DEBUG
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG

---
spring:
  config:
    activate:
      on-profile: docker
  data:
    mongodb:
      host: mongodb
  kafka:
    bootstrap-servers: kafka:9092
  cloud:
    stream:
      kafka:
        binder:
          brokers: kafka
          defaultBrokerPort: 9092
          replication-factor: 1

server:
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:8761/eureka/
    initialInstanceInfoReplicationIntervalSeconds: 5
    registryFetchIntervalSeconds: 5
  instance:
    leaseRenewalIntervalInSeconds: 5
    leaseExpirationDurationInSeconds: 5